import {
  pgTable,
  uuid,
  varchar,
  decimal,
  integer,
  boolean,
  date,
  timestamp,
  pgEnum,
  text,
  unique,
} from 'drizzle-orm/pg-core';

export const paymentFrequencyEnum = pgEnum('payment_frequency', ['MONTHLY', 'QUARTERLY', 'YEARLY']);

export const schemeConfigs = pgTable('scheme_configs', {
  id: uuid('id').primaryKey().defaultRandom(),
  schemeCode: varchar('scheme_code', { length: 50 }).notNull().unique(),
  schemeName: varchar('scheme_name', { length: 150 }).notNull(),
  minProjectCost: decimal('min_project_cost', { precision: 14, scale: 2 }),
  maxProjectCost: decimal('max_project_cost', { precision: 14, scale: 2 }),
  financingPercentage: decimal('financing_percentage', { precision: 6, scale: 3 }),
  maxLoanAmount: decimal('max_loan_amount', { precision: 14, scale: 2 }),
  interestRate: decimal('interest_rate', { precision: 6, scale: 3 }),
  tenureMonths: integer('tenure_months'),
  moratoriumMonths: integer('moratorium_months'),
  paymentFrequency: paymentFrequencyEnum('payment_frequency'),
  beneficiaryType: varchar('beneficiary_type', { length: 100 }),
  incomeLimit: decimal('income_limit', { precision: 14, scale: 2 }),
  effectiveFrom: date('effective_from').notNull(),
  effectiveTo: date('effective_to'),
  sourceName: varchar('source_name', { length: 200 }).notNull(),
  sourceReference: text('source_reference').notNull(),
  isActive: boolean('is_active').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const financialRuns = pgTable('financial_runs', {
  id: uuid('id').primaryKey().defaultRandom(),
  assessmentId: uuid('assessment_id').notNull(),
  schemeConfigId: uuid('scheme_config_id').references(() => schemeConfigs.id),
  projectCost: decimal('project_cost', { precision: 14, scale: 2 }).notNull(),
  ownContribution: decimal('own_contribution', { precision: 14, scale: 2 }).notNull(),
  loanAmount: decimal('loan_amount', { precision: 14, scale: 2 }).notNull(),
  monthlyRevenue: decimal('monthly_revenue', { precision: 14, scale: 2 }),
  monthlyOperatingCost: decimal('monthly_operating_cost', { precision: 14, scale: 2 }),
  interestRate: decimal('interest_rate', { precision: 6, scale: 3 }).notNull(),
  tenureMonths: integer('tenure_months').notNull(),
  moratoriumMonths: integer('moratorium_months').notNull(),
  paymentFrequency: paymentFrequencyEnum('payment_frequency').notNull(),
  emi: decimal('emi', { precision: 14, scale: 2 }),
  installmentAmount: decimal('installment_amount', { precision: 14, scale: 2 }),
  annualDebtService: decimal('annual_debt_service', { precision: 14, scale: 2 }),
  dscr: decimal('dscr', { precision: 8, scale: 4 }),
  totalInterest: decimal('total_interest', { precision: 14, scale: 2 }),
  totalRepayment: decimal('total_repayment', { precision: 14, scale: 2 }),
  calculationVersion: varchar('calculation_version', { length: 30 }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const repaymentScheduleItems = pgTable('repayment_schedule_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  financialRunId: uuid('financial_run_id').notNull().references(() => financialRuns.id),
  sequenceNumber: integer('sequence_number').notNull(),
  periodStart: date('period_start').notNull(),
  periodEnd: date('period_end').notNull(),
  dueDate: date('due_date').notNull(),
  openingPrincipal: decimal('opening_principal', { precision: 14, scale: 2 }).notNull(),
  principalPayment: decimal('principal_payment', { precision: 14, scale: 2 }).notNull(),
  interestPayment: decimal('interest_payment', { precision: 14, scale: 2 }).notNull(),
  installmentAmount: decimal('installment_amount', { precision: 14, scale: 2 }).notNull(),
  closingPrincipal: decimal('closing_principal', { precision: 14, scale: 2 }).notNull(),
  isMoratorium: boolean('is_moratorium').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  unq_run_seq: unique().on(t.financialRunId, t.sequenceNumber),
}));
